apiVersion: v1
kind: Service
metadata:
  name: wsrestgestioncarrito
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  namespace: dev
spec:
  ports:
    - port: 18080
      name: http
      targetPort: 18080
      protocol: TCP
  type: LoadBalancer    
  selector:
    app: wsrestgestioncarrito